config:
  send_anonymous_usage_stats: False
  use_colors: False

scc-bigquery-db:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: temp-vxl8cbhr-wsky
      dataset: dbt_test_dataset
      threads: 4
      keyfile: /home/kevin_ruprecht_wellsky_com/temp-vxl8cbhr-wsky-4b2770cdf6e8.json
      priority: batch