config:
  send_anonymous_usage_stats: False
  use_colors: False

scc-bigquery-db:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: bigquery-public-data
      dataset: sdoh_cdc_wonder_natality
      threads: 4
      keyfile: /Users/kevin.ruprecht/Documents/code/scc-elt-data-modeling/temp-vxl8cbhr-wsky-4b2770cdf6e8.json
      priority: batch