name: dbt_test_project
version: 1.0
config-version: 2

profile: scc-bigquery-db

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets: "target"

models:
  dbt-test-project:
    marts:
      +materialized: table
    staging:
      +materialized: view